//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompShop2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransCode { get; set; }
        public System.DateTime Date { get; set; }
        public int Seller { get; set; }
        public int Thing { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
